//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "accrual_schedules"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: Uuid,
    pub organization_id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub total_amount: Decimal,
    pub currency_id: String,
    pub debit_account_id: Uuid,
    pub credit_account_id: Uuid,
    pub start_date: Date,
    pub end_date: Date,
    pub frequency: String,
    pub total_periods: i32,
    pub periods_processed: i32,
    pub total_amount_recognized: Decimal,
    pub next_run_date: Option<Date>,
    pub status: String,
    pub last_transaction_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    OrganizationId,
    Name,
    Description,
    TotalAmount,
    CurrencyId,
    DebitAccountId,
    CreditAccountId,
    StartDate,
    EndDate,
    Frequency,
    TotalPeriods,
    PeriodsProcessed,
    TotalAmountRecognized,
    NextRunDate,
    Status,
    LastTransactionId,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ChartOfAccounts2,
    ChartOfAccounts1,
    Currencies,
    Organizations,
    Transactions,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::OrganizationId => ColumnType::Uuid.def(),
            Self::Name => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Description => ColumnType::Text.def().null(),
            Self::TotalAmount => ColumnType::Decimal(Some((19u32, 4u32))).def(),
            Self::CurrencyId => ColumnType::Char(Some(3u32)).def(),
            Self::DebitAccountId => ColumnType::Uuid.def(),
            Self::CreditAccountId => ColumnType::Uuid.def(),
            Self::StartDate => ColumnType::Date.def(),
            Self::EndDate => ColumnType::Date.def(),
            Self::Frequency => ColumnType::String(StringLen::N(20u32)).def(),
            Self::TotalPeriods => ColumnType::Integer.def(),
            Self::PeriodsProcessed => ColumnType::Integer.def(),
            Self::TotalAmountRecognized => ColumnType::Decimal(Some((19u32, 4u32))).def(),
            Self::NextRunDate => ColumnType::Date.def().null(),
            Self::Status => ColumnType::String(StringLen::N(20u32)).def(),
            Self::LastTransactionId => ColumnType::Uuid.def().null(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ChartOfAccounts2 => Entity::belongs_to(super::chart_of_accounts::Entity)
                .from(Column::CreditAccountId)
                .to(super::chart_of_accounts::Column::Id)
                .into(),
            Self::ChartOfAccounts1 => Entity::belongs_to(super::chart_of_accounts::Entity)
                .from(Column::DebitAccountId)
                .to(super::chart_of_accounts::Column::Id)
                .into(),
            Self::Currencies => Entity::belongs_to(super::currencies::Entity)
                .from(Column::CurrencyId)
                .to(super::currencies::Column::Code)
                .into(),
            Self::Organizations => Entity::belongs_to(super::organizations::Entity)
                .from(Column::OrganizationId)
                .to(super::organizations::Column::Id)
                .into(),
            Self::Transactions => Entity::belongs_to(super::transactions::Entity)
                .from(Column::LastTransactionId)
                .to(super::transactions::Column::Id)
                .into(),
        }
    }
}

impl Related<super::currencies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Currencies.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
