//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "budget_line_dimensions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub budget_line_id: Uuid,
    pub dimension_value_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::budget_lines::Entity",
        from = "Column::BudgetLineId",
        to = "super::budget_lines::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    BudgetLines,
    #[sea_orm(
        belongs_to = "super::dimension_values::Entity",
        from = "Column::DimensionValueId",
        to = "super::dimension_values::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DimensionValues,
}

impl Related<super::budget_lines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BudgetLines.def()
    }
}

impl Related<super::dimension_values::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DimensionValues.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
