//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "budget_lines")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub budget_id: Uuid,
    pub account_id: Uuid,
    pub fiscal_period_id: Uuid,
    #[sea_orm(column_type = "Decimal(Some((19, 4)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::budget_line_dimensions::Entity")]
    BudgetLineDimensions,
    #[sea_orm(
        belongs_to = "super::budgets::Entity",
        from = "Column::BudgetId",
        to = "super::budgets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Budgets,
    #[sea_orm(
        belongs_to = "super::chart_of_accounts::Entity",
        from = "Column::AccountId",
        to = "super::chart_of_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChartOfAccounts,
    #[sea_orm(
        belongs_to = "super::fiscal_periods::Entity",
        from = "Column::FiscalPeriodId",
        to = "super::fiscal_periods::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    FiscalPeriods,
}

impl Related<super::budget_line_dimensions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BudgetLineDimensions.def()
    }
}

impl Related<super::budgets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Budgets.def()
    }
}

impl Related<super::chart_of_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChartOfAccounts.def()
    }
}

impl Related<super::fiscal_periods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FiscalPeriods.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
