//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::BudgetType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "budgets"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: Uuid,
    pub organization_id: Uuid,
    pub fiscal_year_id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub budget_type: BudgetType,
    pub currency: String,
    pub is_active: bool,
    pub is_locked: bool,
    pub created_by: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    OrganizationId,
    FiscalYearId,
    Name,
    Description,
    BudgetType,
    Currency,
    IsActive,
    IsLocked,
    CreatedBy,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    BudgetLines,
    Currencies,
    FiscalYears,
    Organizations,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::OrganizationId => ColumnType::Uuid.def(),
            Self::FiscalYearId => ColumnType::Uuid.def(),
            Self::Name => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Description => ColumnType::Text.def().null(),
            Self::BudgetType => BudgetType::db_type().get_column_type().to_owned().def(),
            Self::Currency => ColumnType::Char(Some(3u32)).def(),
            Self::IsActive => ColumnType::Boolean.def(),
            Self::IsLocked => ColumnType::Boolean.def(),
            Self::CreatedBy => ColumnType::Uuid.def(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::BudgetLines => Entity::has_many(super::budget_lines::Entity).into(),
            Self::Currencies => Entity::belongs_to(super::currencies::Entity)
                .from(Column::Currency)
                .to(super::currencies::Column::Code)
                .into(),
            Self::FiscalYears => Entity::belongs_to(super::fiscal_years::Entity)
                .from(Column::FiscalYearId)
                .to(super::fiscal_years::Column::Id)
                .into(),
            Self::Organizations => Entity::belongs_to(super::organizations::Entity)
                .from(Column::OrganizationId)
                .to(super::organizations::Column::Id)
                .into(),
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::CreatedBy)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::budget_lines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BudgetLines.def()
    }
}

impl Related<super::currencies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Currencies.def()
    }
}

impl Related<super::fiscal_years::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FiscalYears.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
