//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::AccountSubtype;
use super::sea_orm_active_enums::AccountType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "chart_of_accounts"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: Uuid,
    pub organization_id: Uuid,
    pub entity_id: Uuid,
    pub code: String,
    pub name: String,
    pub description: Option<String>,
    pub account_type: AccountType,
    pub account_subtype: Option<AccountSubtype>,
    pub parent_id: Option<Uuid>,
    pub currency: String,
    pub is_active: bool,
    pub is_system_account: bool,
    pub allow_direct_posting: bool,
    pub is_bank_account: bool,
    pub bank_account_number: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    OrganizationId,
    EntityId,
    Code,
    Name,
    Description,
    AccountType,
    AccountSubtype,
    ParentId,
    Currency,
    IsActive,
    IsSystemAccount,
    AllowDirectPosting,
    IsBankAccount,
    BankAccountNumber,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    BudgetLines,
    SelfRef,
    Currencies,
    Entities,
    LedgerEntries,
    Organizations,
    RevaluationLogs,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::OrganizationId => ColumnType::Uuid.def(),
            Self::EntityId => ColumnType::Uuid.def(),
            Self::Code => ColumnType::String(StringLen::N(20u32)).def(),
            Self::Name => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Description => ColumnType::Text.def().null(),
            Self::AccountType => AccountType::db_type().get_column_type().to_owned().def(),
            Self::AccountSubtype => AccountSubtype::db_type()
                .get_column_type()
                .to_owned()
                .def()
                .null(),
            Self::ParentId => ColumnType::Uuid.def().null(),
            Self::Currency => ColumnType::Char(Some(3u32)).def(),
            Self::IsActive => ColumnType::Boolean.def(),
            Self::IsSystemAccount => ColumnType::Boolean.def(),
            Self::AllowDirectPosting => ColumnType::Boolean.def(),
            Self::IsBankAccount => ColumnType::Boolean.def(),
            Self::BankAccountNumber => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::BudgetLines => Entity::has_many(super::budget_lines::Entity).into(),
            Self::SelfRef => Entity::belongs_to(Entity)
                .from(Column::ParentId)
                .to(Column::Id)
                .into(),
            Self::Currencies => Entity::belongs_to(super::currencies::Entity)
                .from(Column::Currency)
                .to(super::currencies::Column::Code)
                .into(),
            Self::Entities => Entity::belongs_to(super::entities::Entity)
                .from(Column::EntityId)
                .to(super::entities::Column::Id)
                .into(),
            Self::LedgerEntries => Entity::has_many(super::ledger_entries::Entity).into(),
            Self::Organizations => Entity::belongs_to(super::organizations::Entity)
                .from(Column::OrganizationId)
                .to(super::organizations::Column::Id)
                .into(),
            Self::RevaluationLogs => Entity::has_many(super::revaluation_logs::Entity).into(),
        }
    }
}

impl Related<super::budget_lines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BudgetLines.def()
    }
}

impl Related<super::currencies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Currencies.def()
    }
}

impl Related<super::entities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Entities.def()
    }
}

impl Related<super::ledger_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LedgerEntries.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::revaluation_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RevaluationLogs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
