//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "dimension_values")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub organization_id: Uuid,
    pub dimension_type_id: Uuid,
    pub code: String,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub parent_id: Option<Uuid>,
    pub is_active: bool,
    pub effective_from: Option<Date>,
    pub effective_to: Option<Date>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::budget_line_dimensions::Entity")]
    BudgetLineDimensions,
    #[sea_orm(
        belongs_to = "super::dimension_types::Entity",
        from = "Column::DimensionTypeId",
        to = "super::dimension_types::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    DimensionTypes,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::entry_dimensions::Entity")]
    EntryDimensions,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::budget_line_dimensions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BudgetLineDimensions.def()
    }
}

impl Related<super::dimension_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DimensionTypes.def()
    }
}

impl Related<super::entry_dimensions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EntryDimensions.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
