//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "entry_dimensions"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: Uuid,
    pub ledger_entry_id: Uuid,
    pub dimension_value_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    LedgerEntryId,
    DimensionValueId,
    CreatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    DimensionValues,
    LedgerEntries,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::LedgerEntryId => ColumnType::Uuid.def(),
            Self::DimensionValueId => ColumnType::Uuid.def(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::DimensionValues => Entity::belongs_to(super::dimension_values::Entity)
                .from(Column::DimensionValueId)
                .to(super::dimension_values::Column::Id)
                .into(),
            Self::LedgerEntries => Entity::belongs_to(super::ledger_entries::Entity)
                .from(Column::LedgerEntryId)
                .to(super::ledger_entries::Column::Id)
                .into(),
        }
    }
}

impl Related<super::dimension_values::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DimensionValues.def()
    }
}

impl Related<super::ledger_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LedgerEntries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
