//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::FiscalYearStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "fiscal_years"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: Uuid,
    pub organization_id: Uuid,
    pub entity_id: Uuid,
    pub name: String,
    pub start_date: Date,
    pub end_date: Date,
    pub status: FiscalYearStatus,
    pub closed_by: Option<Uuid>,
    pub closed_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    OrganizationId,
    EntityId,
    Name,
    StartDate,
    EndDate,
    Status,
    ClosedBy,
    ClosedAt,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Budgets,
    Entities,
    FiscalPeriods,
    Organizations,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::OrganizationId => ColumnType::Uuid.def(),
            Self::EntityId => ColumnType::Uuid.def(),
            Self::Name => ColumnType::String(StringLen::N(50u32)).def(),
            Self::StartDate => ColumnType::Date.def(),
            Self::EndDate => ColumnType::Date.def(),
            Self::Status => FiscalYearStatus::db_type()
                .get_column_type()
                .to_owned()
                .def(),
            Self::ClosedBy => ColumnType::Uuid.def().null(),
            Self::ClosedAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Budgets => Entity::has_many(super::budgets::Entity).into(),
            Self::Entities => Entity::belongs_to(super::entities::Entity)
                .from(Column::EntityId)
                .to(super::entities::Column::Id)
                .into(),
            Self::FiscalPeriods => Entity::has_many(super::fiscal_periods::Entity).into(),
            Self::Organizations => Entity::belongs_to(super::organizations::Entity)
                .from(Column::OrganizationId)
                .to(super::organizations::Column::Id)
                .into(),
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::ClosedBy)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::budgets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Budgets.def()
    }
}

impl Related<super::entities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Entities.def()
    }
}

impl Related<super::fiscal_periods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FiscalPeriods.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
