//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::FiscalPeriodStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "fiscal_periods")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub organization_id: Uuid,
    pub fiscal_year_id: Uuid,
    pub name: String,
    pub period_number: i16,
    pub start_date: Date,
    pub end_date: Date,
    pub status: FiscalPeriodStatus,
    pub is_adjustment_period: bool,
    pub closed_by: Option<Uuid>,
    pub closed_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::budget_lines::Entity")]
    BudgetLines,
    #[sea_orm(
        belongs_to = "super::fiscal_years::Entity",
        from = "Column::FiscalYearId",
        to = "super::fiscal_years::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    FiscalYears,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(has_many = "super::transactions::Entity")]
    Transactions,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ClosedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::budget_lines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BudgetLines.def()
    }
}

impl Related<super::fiscal_years::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FiscalYears.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
