//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "intercompany_mappings"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: Uuid,
    pub source_entity_id: Uuid,
    pub target_entity_id: Uuid,
    pub source_account_id: Uuid,
    pub target_account_id: Uuid,
    pub mapping_type: String,
    pub auto_post: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    SourceEntityId,
    TargetEntityId,
    SourceAccountId,
    TargetAccountId,
    MappingType,
    AutoPost,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ChartOfAccounts2,
    ChartOfAccounts1,
    Entities2,
    Entities1,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::SourceEntityId => ColumnType::Uuid.def(),
            Self::TargetEntityId => ColumnType::Uuid.def(),
            Self::SourceAccountId => ColumnType::Uuid.def(),
            Self::TargetAccountId => ColumnType::Uuid.def(),
            Self::MappingType => ColumnType::String(StringLen::N(20u32)).def(),
            Self::AutoPost => ColumnType::Boolean.def(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ChartOfAccounts2 => Entity::belongs_to(super::chart_of_accounts::Entity)
                .from(Column::SourceAccountId)
                .to(super::chart_of_accounts::Column::Id)
                .into(),
            Self::ChartOfAccounts1 => Entity::belongs_to(super::chart_of_accounts::Entity)
                .from(Column::TargetAccountId)
                .to(super::chart_of_accounts::Column::Id)
                .into(),
            Self::Entities2 => Entity::belongs_to(super::entities::Entity)
                .from(Column::SourceEntityId)
                .to(super::entities::Column::Id)
                .into(),
            Self::Entities1 => Entity::belongs_to(super::entities::Entity)
                .from(Column::TargetEntityId)
                .to(super::entities::Column::Id)
                .into(),
        }
    }
}

impl ActiveModelBehavior for ActiveModel {}
