//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ledger_entries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub transaction_id: Uuid,
    pub account_id: Uuid,
    pub source_currency: String,
    #[sea_orm(column_type = "Decimal(Some((19, 4)))")]
    pub source_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((19, 10)))")]
    pub exchange_rate: Decimal,
    pub functional_currency: String,
    #[sea_orm(column_type = "Decimal(Some((19, 4)))")]
    pub functional_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((19, 4)))")]
    pub debit: Decimal,
    #[sea_orm(column_type = "Decimal(Some((19, 4)))")]
    pub credit: Decimal,
    pub account_version: i64,
    #[sea_orm(column_type = "Decimal(Some((19, 4)))")]
    pub account_previous_balance: Decimal,
    #[sea_orm(column_type = "Decimal(Some((19, 4)))")]
    pub account_current_balance: Decimal,
    pub memo: Option<String>,
    pub event_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chart_of_accounts::Entity",
        from = "Column::AccountId",
        to = "super::chart_of_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChartOfAccounts,
    #[sea_orm(
        belongs_to = "super::currencies::Entity",
        from = "Column::FunctionalCurrency",
        to = "super::currencies::Column::Code",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Currencies2,
    #[sea_orm(
        belongs_to = "super::currencies::Entity",
        from = "Column::SourceCurrency",
        to = "super::currencies::Column::Code",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Currencies1,
    #[sea_orm(has_many = "super::entry_dimensions::Entity")]
    EntryDimensions,
    #[sea_orm(
        belongs_to = "super::transactions::Entity",
        from = "Column::TransactionId",
        to = "super::transactions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Transactions,
}

impl Related<super::chart_of_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChartOfAccounts.def()
    }
}

impl Related<super::entry_dimensions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EntryDimensions.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
