//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "ledger_entries"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: Uuid,
    pub entity_id: Uuid,
    pub transaction_id: Uuid,
    pub account_id: Uuid,
    pub source_currency: String,
    pub source_amount: Decimal,
    pub exchange_rate: Decimal,
    pub functional_currency: String,
    pub functional_amount: Decimal,
    pub debit: Decimal,
    pub credit: Decimal,
    pub account_version: i64,
    pub account_previous_balance: Decimal,
    pub account_current_balance: Decimal,
    pub memo: Option<String>,
    pub event_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub entry_hash: Option<String>,
    pub previous_entry_hash: Option<String>,
    pub compliance_metadata: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    EntityId,
    TransactionId,
    AccountId,
    SourceCurrency,
    SourceAmount,
    ExchangeRate,
    FunctionalCurrency,
    FunctionalAmount,
    Debit,
    Credit,
    AccountVersion,
    AccountPreviousBalance,
    AccountCurrentBalance,
    Memo,
    EventAt,
    CreatedAt,
    EntryHash,
    PreviousEntryHash,
    ComplianceMetadata,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ChartOfAccounts,
    Currencies2,
    Currencies1,
    Entities,
    EntryDimensions,
    Transactions,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::EntityId => ColumnType::Uuid.def(),
            Self::TransactionId => ColumnType::Uuid.def(),
            Self::AccountId => ColumnType::Uuid.def(),
            Self::SourceCurrency => ColumnType::Char(Some(3u32)).def(),
            Self::SourceAmount => ColumnType::Decimal(Some((19u32, 4u32))).def(),
            Self::ExchangeRate => ColumnType::Decimal(Some((19u32, 10u32))).def(),
            Self::FunctionalCurrency => ColumnType::Char(Some(3u32)).def(),
            Self::FunctionalAmount => ColumnType::Decimal(Some((19u32, 4u32))).def(),
            Self::Debit => ColumnType::Decimal(Some((19u32, 4u32))).def(),
            Self::Credit => ColumnType::Decimal(Some((19u32, 4u32))).def(),
            Self::AccountVersion => ColumnType::BigInteger.def(),
            Self::AccountPreviousBalance => ColumnType::Decimal(Some((19u32, 4u32))).def(),
            Self::AccountCurrentBalance => ColumnType::Decimal(Some((19u32, 4u32))).def(),
            Self::Memo => ColumnType::String(StringLen::N(500u32)).def().null(),
            Self::EventAt => ColumnType::TimestampWithTimeZone.def(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::EntryHash => ColumnType::String(StringLen::N(64u32)).def().null(),
            Self::PreviousEntryHash => ColumnType::String(StringLen::N(64u32)).def().null(),
            Self::ComplianceMetadata => ColumnType::JsonBinary.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ChartOfAccounts => Entity::belongs_to(super::chart_of_accounts::Entity)
                .from(Column::AccountId)
                .to(super::chart_of_accounts::Column::Id)
                .into(),
            Self::Currencies2 => Entity::belongs_to(super::currencies::Entity)
                .from(Column::FunctionalCurrency)
                .to(super::currencies::Column::Code)
                .into(),
            Self::Currencies1 => Entity::belongs_to(super::currencies::Entity)
                .from(Column::SourceCurrency)
                .to(super::currencies::Column::Code)
                .into(),
            Self::Entities => Entity::belongs_to(super::entities::Entity)
                .from(Column::EntityId)
                .to(super::entities::Column::Id)
                .into(),
            Self::EntryDimensions => Entity::has_many(super::entry_dimensions::Entity).into(),
            Self::Transactions => Entity::belongs_to(super::transactions::Entity)
                .from(Column::TransactionId)
                .to(super::transactions::Column::Id)
                .into(),
        }
    }
}

impl Related<super::chart_of_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChartOfAccounts.def()
    }
}

impl Related<super::entry_dimensions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EntryDimensions.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
