//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19
//!
//! This module contains auto-generated `SeaORM` entities.
//! Documentation warnings are suppressed for generated code.

#![allow(missing_docs)]
#![allow(clippy::struct_excessive_bools)]

pub mod prelude;

pub mod approval_rules;
pub mod attachments;
pub mod budget_line_dimensions;
pub mod budget_lines;
pub mod budgets;
pub mod chart_of_accounts;
pub mod currencies;
pub mod dimension_types;
pub mod dimension_values;
pub mod email_verification_tokens;
pub mod entry_dimensions;
pub mod exchange_rates;
pub mod fiscal_periods;
pub mod fiscal_years;
pub mod ledger_entries;
pub mod organization_usage;
pub mod organization_users;
pub mod organizations;
pub mod sea_orm_active_enums;
pub mod sessions;
pub mod tier_limits;
pub mod transactions;
pub mod users;
