//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::SubscriptionStatus;
use super::sea_orm_active_enums::SubscriptionTier;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "organizations"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: Uuid,
    pub name: String,
    pub slug: String,
    pub base_currency: String,
    pub timezone: String,
    pub settings: Json,
    pub is_active: bool,
    pub subscription_tier: SubscriptionTier,
    pub subscription_status: SubscriptionStatus,
    pub trial_ends_at: Option<DateTimeWithTimeZone>,
    pub subscription_ends_at: Option<DateTimeWithTimeZone>,
    pub payment_provider: Option<String>,
    pub payment_customer_id: Option<String>,
    pub payment_subscription_id: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    Slug,
    BaseCurrency,
    Timezone,
    Settings,
    IsActive,
    SubscriptionTier,
    SubscriptionStatus,
    TrialEndsAt,
    SubscriptionEndsAt,
    PaymentProvider,
    PaymentCustomerId,
    PaymentSubscriptionId,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ApprovalRules,
    Attachments,
    Budgets,
    ChartOfAccounts,
    DimensionTypes,
    DimensionValues,
    ExchangeRates,
    FiscalPeriods,
    FiscalYears,
    OrganizationUsage,
    OrganizationUsers,
    Sessions,
    Transactions,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::Name => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Slug => ColumnType::String(StringLen::N(100u32)).def().unique(),
            Self::BaseCurrency => ColumnType::Char(Some(3u32)).def(),
            Self::Timezone => ColumnType::String(StringLen::N(50u32)).def(),
            Self::Settings => ColumnType::JsonBinary.def(),
            Self::IsActive => ColumnType::Boolean.def(),
            Self::SubscriptionTier => SubscriptionTier::db_type()
                .get_column_type()
                .to_owned()
                .def(),
            Self::SubscriptionStatus => SubscriptionStatus::db_type()
                .get_column_type()
                .to_owned()
                .def(),
            Self::TrialEndsAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::SubscriptionEndsAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::PaymentProvider => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::PaymentCustomerId => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::PaymentSubscriptionId => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ApprovalRules => Entity::has_many(super::approval_rules::Entity).into(),
            Self::Attachments => Entity::has_many(super::attachments::Entity).into(),
            Self::Budgets => Entity::has_many(super::budgets::Entity).into(),
            Self::ChartOfAccounts => Entity::has_many(super::chart_of_accounts::Entity).into(),
            Self::DimensionTypes => Entity::has_many(super::dimension_types::Entity).into(),
            Self::DimensionValues => Entity::has_many(super::dimension_values::Entity).into(),
            Self::ExchangeRates => Entity::has_many(super::exchange_rates::Entity).into(),
            Self::FiscalPeriods => Entity::has_many(super::fiscal_periods::Entity).into(),
            Self::FiscalYears => Entity::has_many(super::fiscal_years::Entity).into(),
            Self::OrganizationUsage => Entity::has_many(super::organization_usage::Entity).into(),
            Self::OrganizationUsers => Entity::has_many(super::organization_users::Entity).into(),
            Self::Sessions => Entity::has_many(super::sessions::Entity).into(),
            Self::Transactions => Entity::has_many(super::transactions::Entity).into(),
        }
    }
}

impl Related<super::approval_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApprovalRules.def()
    }
}

impl Related<super::attachments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Attachments.def()
    }
}

impl Related<super::budgets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Budgets.def()
    }
}

impl Related<super::chart_of_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChartOfAccounts.def()
    }
}

impl Related<super::dimension_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DimensionTypes.def()
    }
}

impl Related<super::dimension_values::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DimensionValues.def()
    }
}

impl Related<super::exchange_rates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExchangeRates.def()
    }
}

impl Related<super::fiscal_periods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FiscalPeriods.def()
    }
}

impl Related<super::fiscal_years::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FiscalYears.def()
    }
}

impl Related<super::organization_usage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationUsage.def()
    }
}

impl Related<super::organization_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationUsers.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::organization_users::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::organization_users::Relation::Organizations
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
