//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::SubscriptionStatus;
use super::sea_orm_active_enums::SubscriptionTier;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "organizations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    #[sea_orm(unique)]
    pub slug: String,
    pub base_currency: String,
    pub timezone: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub settings: Json,
    pub is_active: bool,
    pub subscription_tier: SubscriptionTier,
    pub subscription_status: SubscriptionStatus,
    pub trial_ends_at: Option<DateTimeWithTimeZone>,
    pub subscription_ends_at: Option<DateTimeWithTimeZone>,
    pub payment_provider: Option<String>,
    pub payment_customer_id: Option<String>,
    pub payment_subscription_id: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::approval_rules::Entity")]
    ApprovalRules,
    #[sea_orm(has_many = "super::attachments::Entity")]
    Attachments,
    #[sea_orm(has_many = "super::budgets::Entity")]
    Budgets,
    #[sea_orm(has_many = "super::chart_of_accounts::Entity")]
    ChartOfAccounts,
    #[sea_orm(has_many = "super::dimension_types::Entity")]
    DimensionTypes,
    #[sea_orm(has_many = "super::dimension_values::Entity")]
    DimensionValues,
    #[sea_orm(has_many = "super::exchange_rates::Entity")]
    ExchangeRates,
    #[sea_orm(has_many = "super::fiscal_periods::Entity")]
    FiscalPeriods,
    #[sea_orm(has_many = "super::fiscal_years::Entity")]
    FiscalYears,
    #[sea_orm(has_many = "super::organization_usage::Entity")]
    OrganizationUsage,
    #[sea_orm(has_many = "super::organization_users::Entity")]
    OrganizationUsers,
    #[sea_orm(has_many = "super::transactions::Entity")]
    Transactions,
}

impl Related<super::approval_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApprovalRules.def()
    }
}

impl Related<super::attachments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Attachments.def()
    }
}

impl Related<super::budgets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Budgets.def()
    }
}

impl Related<super::chart_of_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChartOfAccounts.def()
    }
}

impl Related<super::dimension_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DimensionTypes.def()
    }
}

impl Related<super::dimension_values::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DimensionValues.def()
    }
}

impl Related<super::exchange_rates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExchangeRates.def()
    }
}

impl Related<super::fiscal_periods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FiscalPeriods.def()
    }
}

impl Related<super::fiscal_years::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FiscalYears.def()
    }
}

impl Related<super::organization_usage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationUsage.def()
    }
}

impl Related<super::organization_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationUsers.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::organization_users::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::organization_users::Relation::Organizations
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
