//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "revaluation_logs"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: Uuid,
    pub organization_id: Uuid,
    pub account_id: Uuid,
    pub revaluation_date: Date,
    pub currency_id: String,
    pub balance_in_currency: Decimal,
    pub old_exchange_rate: Decimal,
    pub new_exchange_rate: Decimal,
    pub unrealized_gain_loss: Decimal,
    pub transaction_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    OrganizationId,
    AccountId,
    RevaluationDate,
    CurrencyId,
    BalanceInCurrency,
    OldExchangeRate,
    NewExchangeRate,
    UnrealizedGainLoss,
    TransactionId,
    CreatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ChartOfAccounts,
    Currencies,
    Organizations,
    Transactions,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::OrganizationId => ColumnType::Uuid.def(),
            Self::AccountId => ColumnType::Uuid.def(),
            Self::RevaluationDate => ColumnType::Date.def(),
            Self::CurrencyId => ColumnType::Char(Some(3u32)).def(),
            Self::BalanceInCurrency => ColumnType::Decimal(Some((19u32, 4u32))).def(),
            Self::OldExchangeRate => ColumnType::Decimal(Some((19u32, 10u32))).def(),
            Self::NewExchangeRate => ColumnType::Decimal(Some((19u32, 10u32))).def(),
            Self::UnrealizedGainLoss => ColumnType::Decimal(Some((19u32, 4u32))).def(),
            Self::TransactionId => ColumnType::Uuid.def().null(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ChartOfAccounts => Entity::belongs_to(super::chart_of_accounts::Entity)
                .from(Column::AccountId)
                .to(super::chart_of_accounts::Column::Id)
                .into(),
            Self::Currencies => Entity::belongs_to(super::currencies::Entity)
                .from(Column::CurrencyId)
                .to(super::currencies::Column::Code)
                .into(),
            Self::Organizations => Entity::belongs_to(super::organizations::Entity)
                .from(Column::OrganizationId)
                .to(super::organizations::Column::Id)
                .into(),
            Self::Transactions => Entity::belongs_to(super::transactions::Entity)
                .from(Column::TransactionId)
                .to(super::transactions::Column::Id)
                .into(),
        }
    }
}

impl Related<super::chart_of_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChartOfAccounts.def()
    }
}

impl Related<super::currencies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Currencies.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
