//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "account_subtype")]
pub enum AccountSubtype {
    #[sea_orm(string_value = "cash")]
    Cash,
    #[sea_orm(string_value = "bank")]
    Bank,
    #[sea_orm(string_value = "accounts_receivable")]
    AccountsReceivable,
    #[sea_orm(string_value = "inventory")]
    Inventory,
    #[sea_orm(string_value = "prepaid")]
    Prepaid,
    #[sea_orm(string_value = "fixed_asset")]
    FixedAsset,
    #[sea_orm(string_value = "accumulated_depreciation")]
    AccumulatedDepreciation,
    #[sea_orm(string_value = "other_asset")]
    OtherAsset,
    #[sea_orm(string_value = "accounts_payable")]
    AccountsPayable,
    #[sea_orm(string_value = "credit_card")]
    CreditCard,
    #[sea_orm(string_value = "accrued_liability")]
    AccruedLiability,
    #[sea_orm(string_value = "short_term_debt")]
    ShortTermDebt,
    #[sea_orm(string_value = "long_term_debt")]
    LongTermDebt,
    #[sea_orm(string_value = "other_liability")]
    OtherLiability,
    #[sea_orm(string_value = "owner_equity")]
    OwnerEquity,
    #[sea_orm(string_value = "retained_earnings")]
    RetainedEarnings,
    #[sea_orm(string_value = "common_stock")]
    CommonStock,
    #[sea_orm(string_value = "other_equity")]
    OtherEquity,
    #[sea_orm(string_value = "operating_revenue")]
    OperatingRevenue,
    #[sea_orm(string_value = "other_revenue")]
    OtherRevenue,
    #[sea_orm(string_value = "cost_of_goods_sold")]
    CostOfGoodsSold,
    #[sea_orm(string_value = "operating_expense")]
    OperatingExpense,
    #[sea_orm(string_value = "payroll_expense")]
    PayrollExpense,
    #[sea_orm(string_value = "depreciation_expense")]
    DepreciationExpense,
    #[sea_orm(string_value = "interest_expense")]
    InterestExpense,
    #[sea_orm(string_value = "tax_expense")]
    TaxExpense,
    #[sea_orm(string_value = "other_expense")]
    OtherExpense,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "account_type")]
pub enum AccountType {
    #[sea_orm(string_value = "asset")]
    Asset,
    #[sea_orm(string_value = "liability")]
    Liability,
    #[sea_orm(string_value = "equity")]
    Equity,
    #[sea_orm(string_value = "revenue")]
    Revenue,
    #[sea_orm(string_value = "expense")]
    Expense,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "attachment_type")]
pub enum AttachmentType {
    #[sea_orm(string_value = "receipt")]
    Receipt,
    #[sea_orm(string_value = "invoice")]
    Invoice,
    #[sea_orm(string_value = "contract")]
    Contract,
    #[sea_orm(string_value = "supporting_document")]
    SupportingDocument,
    #[sea_orm(string_value = "other")]
    Other,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "budget_type")]
pub enum BudgetType {
    #[sea_orm(string_value = "annual")]
    Annual,
    #[sea_orm(string_value = "quarterly")]
    Quarterly,
    #[sea_orm(string_value = "monthly")]
    Monthly,
    #[sea_orm(string_value = "project")]
    Project,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "fiscal_period_status"
)]
pub enum FiscalPeriodStatus {
    #[sea_orm(string_value = "OPEN")]
    Open,
    #[sea_orm(string_value = "SOFT_CLOSE")]
    SoftClose,
    #[sea_orm(string_value = "CLOSED")]
    Closed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "fiscal_year_status")]
pub enum FiscalYearStatus {
    #[sea_orm(string_value = "OPEN")]
    Open,
    #[sea_orm(string_value = "CLOSED")]
    Closed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "rate_source")]
pub enum RateSource {
    #[sea_orm(string_value = "manual")]
    Manual,
    #[sea_orm(string_value = "api")]
    Api,
    #[sea_orm(string_value = "bank_feed")]
    BankFeed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "storage_provider")]
pub enum StorageProvider {
    #[sea_orm(string_value = "cloudflare_r2")]
    CloudflareR2,
    #[sea_orm(string_value = "aws_s3")]
    AwsS3,
    #[sea_orm(string_value = "azure_blob")]
    AzureBlob,
    #[sea_orm(string_value = "digitalocean_spaces")]
    DigitaloceanSpaces,
    #[sea_orm(string_value = "supabase_storage")]
    SupabaseStorage,
    #[sea_orm(string_value = "local")]
    Local,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "subscription_status"
)]
pub enum SubscriptionStatus {
    #[sea_orm(string_value = "trialing")]
    Trialing,
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "past_due")]
    PastDue,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
    #[sea_orm(string_value = "expired")]
    Expired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "subscription_tier")]
pub enum SubscriptionTier {
    #[sea_orm(string_value = "starter")]
    Starter,
    #[sea_orm(string_value = "growth")]
    Growth,
    #[sea_orm(string_value = "enterprise")]
    Enterprise,
    #[sea_orm(string_value = "self_hosted")]
    SelfHosted,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "transaction_status")]
pub enum TransactionStatus {
    #[sea_orm(string_value = "draft")]
    Draft,
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "approved")]
    Approved,
    #[sea_orm(string_value = "posted")]
    Posted,
    #[sea_orm(string_value = "voided")]
    Voided,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "transaction_type")]
pub enum TransactionType {
    #[sea_orm(string_value = "journal")]
    Journal,
    #[sea_orm(string_value = "expense")]
    Expense,
    #[sea_orm(string_value = "invoice")]
    Invoice,
    #[sea_orm(string_value = "bill")]
    Bill,
    #[sea_orm(string_value = "payment")]
    Payment,
    #[sea_orm(string_value = "transfer")]
    Transfer,
    #[sea_orm(string_value = "adjustment")]
    Adjustment,
    #[sea_orm(string_value = "opening_balance")]
    OpeningBalance,
    #[sea_orm(string_value = "reversal")]
    Reversal,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_role")]
pub enum UserRole {
    #[sea_orm(string_value = "owner")]
    Owner,
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "accountant")]
    Accountant,
    #[sea_orm(string_value = "approver")]
    Approver,
    #[sea_orm(string_value = "viewer")]
    Viewer,
    #[sea_orm(string_value = "submitter")]
    Submitter,
}
