//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::SubscriptionTier;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tier_limits")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tier: SubscriptionTier,
    pub max_users: Option<i32>,
    pub max_transactions_per_month: Option<i32>,
    pub max_dimensions: i32,
    pub max_currencies: i32,
    pub max_fiscal_periods: Option<i32>,
    pub max_budgets: Option<i32>,
    pub max_approval_rules: Option<i32>,
    pub has_multi_currency: bool,
    pub has_simulation: bool,
    pub has_api_access: bool,
    pub has_sso: bool,
    pub has_custom_reports: bool,
    pub has_multi_entity: bool,
    pub has_audit_export: bool,
    pub has_priority_support: bool,
    pub audit_log_retention_days: i32,
    pub attachment_storage_gb: i32,
    pub display_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
