//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::TransactionStatus;
use super::sea_orm_active_enums::TransactionType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "transactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub organization_id: Uuid,
    pub fiscal_period_id: Uuid,
    pub reference_number: Option<String>,
    pub transaction_type: TransactionType,
    pub transaction_date: Date,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub memo: Option<String>,
    pub status: TransactionStatus,
    pub created_by: Uuid,
    pub submitted_at: Option<DateTimeWithTimeZone>,
    pub submitted_by: Option<Uuid>,
    pub approved_at: Option<DateTimeWithTimeZone>,
    pub approved_by: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub approval_notes: Option<String>,
    pub posted_at: Option<DateTimeWithTimeZone>,
    pub posted_by: Option<Uuid>,
    pub voided_at: Option<DateTimeWithTimeZone>,
    pub voided_by: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub void_reason: Option<String>,
    pub reversed_by_transaction_id: Option<Uuid>,
    pub reverses_transaction_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attachments::Entity")]
    Attachments,
    #[sea_orm(
        belongs_to = "super::fiscal_periods::Entity",
        from = "Column::FiscalPeriodId",
        to = "super::fiscal_periods::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    FiscalPeriods,
    #[sea_orm(has_many = "super::ledger_entries::Entity")]
    LedgerEntries,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ReversedByTransactionId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef2,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ReversesTransactionId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef1,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ApprovedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users5,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users4,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::PostedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users3,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::SubmittedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::VoidedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
}

impl Related<super::attachments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Attachments.def()
    }
}

impl Related<super::fiscal_periods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FiscalPeriods.def()
    }
}

impl Related<super::ledger_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LedgerEntries.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
