//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::SubscriptionStatus;
use super::sea_orm_active_enums::SubscriptionTier;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "users"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: Uuid,
    pub email: String,
    pub password_hash: String,
    pub full_name: String,
    pub is_active: bool,
    pub email_verified_at: Option<DateTimeWithTimeZone>,
    pub subscription_tier: SubscriptionTier,
    pub subscription_status: SubscriptionStatus,
    pub trial_ends_at: Option<DateTimeWithTimeZone>,
    pub subscription_ends_at: Option<DateTimeWithTimeZone>,
    pub payment_provider: Option<String>,
    pub payment_customer_id: Option<String>,
    pub payment_subscription_id: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Email,
    PasswordHash,
    FullName,
    IsActive,
    EmailVerifiedAt,
    SubscriptionTier,
    SubscriptionStatus,
    TrialEndsAt,
    SubscriptionEndsAt,
    PaymentProvider,
    PaymentCustomerId,
    PaymentSubscriptionId,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Attachments,
    Budgets,
    EmailVerificationTokens,
    ExchangeRates,
    FiscalPeriods,
    FiscalYears,
    OrganizationUsers,
    Sessions,
    TierLimits,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::Email => ColumnType::String(StringLen::N(255u32)).def().unique(),
            Self::PasswordHash => ColumnType::String(StringLen::N(255u32)).def(),
            Self::FullName => ColumnType::String(StringLen::N(255u32)).def(),
            Self::IsActive => ColumnType::Boolean.def(),
            Self::EmailVerifiedAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::SubscriptionTier => SubscriptionTier::db_type()
                .get_column_type()
                .to_owned()
                .def(),
            Self::SubscriptionStatus => SubscriptionStatus::db_type()
                .get_column_type()
                .to_owned()
                .def(),
            Self::TrialEndsAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::SubscriptionEndsAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::PaymentProvider => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::PaymentCustomerId => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::PaymentSubscriptionId => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Attachments => Entity::has_many(super::attachments::Entity).into(),
            Self::Budgets => Entity::has_many(super::budgets::Entity).into(),
            Self::EmailVerificationTokens => {
                Entity::has_many(super::email_verification_tokens::Entity).into()
            }
            Self::ExchangeRates => Entity::has_many(super::exchange_rates::Entity).into(),
            Self::FiscalPeriods => Entity::has_many(super::fiscal_periods::Entity).into(),
            Self::FiscalYears => Entity::has_many(super::fiscal_years::Entity).into(),
            Self::OrganizationUsers => Entity::has_many(super::organization_users::Entity).into(),
            Self::Sessions => Entity::has_many(super::sessions::Entity).into(),
            Self::TierLimits => Entity::belongs_to(super::tier_limits::Entity)
                .from(Column::SubscriptionTier)
                .to(super::tier_limits::Column::Tier)
                .into(),
        }
    }
}

impl Related<super::attachments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Attachments.def()
    }
}

impl Related<super::budgets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Budgets.def()
    }
}

impl Related<super::email_verification_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmailVerificationTokens.def()
    }
}

impl Related<super::exchange_rates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExchangeRates.def()
    }
}

impl Related<super::fiscal_periods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FiscalPeriods.def()
    }
}

impl Related<super::fiscal_years::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FiscalYears.def()
    }
}

impl Related<super::organization_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationUsers.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::tier_limits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TierLimits.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        super::organization_users::Relation::Organizations.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::organization_users::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
